display_name: Moonforge

icon: assets/icon/Moonforge-Logo-purple.appiconset/Moonforge-Logo-purple_512.png

keywords:
  - Moonforge
  - Dungeons & Dragons
  - Campaign Manager

generic_name: DnD Campaign Manager

actions:
#  - name: Say Hi
#    label: say-hi
#    arguments:
#      - --say
#      - hi
#  - name: Say Bye
#    label: say-bye
#    arguments:
#      - --say
#      - bye

categories:
  - Utility

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# fastforge automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: [ ]
# You can also specify [metainfo](https://www.freedesktop.org/software/appstream/metainfocreator/#/) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml