display_name: Moonforge
publisher_display_name: BruckCode
identity_name: BruckCode.Moonforge
publisher: CN=D596F5C0-2AA1-4CF6-8BE0-66076479EC9E
msix_version: 0.6.0.0
capabilities: internetClient, webcam, userNotificationListener
logo_path: "assets/icon/Moonforge-Icon-purple.appiconset/Moonforge-Icon-purple_512.png"
languages: de-de, en-us
store: true
output_path: dist
output_name: moonforge-store
certificate_path: D:\Nextcloud\04 BruckCode\Certificates\CERTIFICATE-BRUCKCODE.pfx
app_uri_handler_hosts: moonforge.de